# Generated by Django 3.0.2 on 2020-01-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyexchange', '0002_auto_20191017_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usercurrency',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
